library widgets;

import 'dart:io';
import 'dart:ui';

import 'package:cached_network_image/cached_network_image.dart';
import 'package:date_time_picker/date_time_picker.dart';
import 'package:dh_employer/src/core/params/params.dart';
import 'package:dh_employer/src/core/utils/db_utils.dart';
import 'package:dropdown_search/dropdown_search.dart';
import 'package:firebase_auth/firebase_auth.dart' as kFirebaseUser;
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter/src/widgets/async.dart' as k_connection_state;
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_slidable/flutter_slidable.dart';
import 'package:get/get.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:gradient_borders/box_borders/gradient_box_border.dart';
import 'package:hive/hive.dart';
import 'package:iconsax/iconsax.dart';
import 'package:intl/date_symbol_data_local.dart';
import 'package:outline_gradient_button/outline_gradient_button.dart';
import 'package:sign_in_with_apple/sign_in_with_apple.dart';
import 'package:skeleton_text/skeleton_text.dart';
import 'package:video_player/video_player.dart';

import '../../config/routes/routes.dart';
import '../../core/utils/authenication.dart';
import '../../core/utils/configs_key_helper.dart';
import '../../core/utils/string_utils.dart';
import '../../data/models/models.dart';
import '../../domain/entities/entities.dart';
import '../../domain/entities/entities.dart' as noti;
import '../blocs/blocs.dart';
import '../values/values.dart';
import '../views/candidate/components/employer_flag.dart';

part 'academic_qualification_dropdown_item.dart';
part 'app_comment_skeleton.dart';
part 'availability_status_dropdown.dart';
part 'continue_with.dart';
part 'country_dropdown_item.dart';
part 'currency_dropdown_item.dart';
part 'custom_check_box.dart';
part 'custom_dialog_simple.dart';
part 'custom_icon_button.dart';
part 'custom_image_view.dart';
part 'custom_outline_button.dart';
part 'custom_primary_button.dart';
part 'custom_text_field.dart';
part 'custom_time_picker.dart';
part 'custom_video_view.dart';
part 'custom_year_picker.dart';
part 'dropdown_item.dart';
part 'family_status_dropdown_item.dart';
part 'hero_image.dart';
part 'info_popup.dart';
part 'language_dropdown_item.dart';
part 'loading_scaffold.dart';
part 'member_type_dropdown.dart';
part 'notification_dropdown.dart';
part 'phone_number_dropdown_item.dart';
part 'religion_dropdown_item.dart';
part 'rest_day_dropdown_item.dart';
part 'saved_search_dropdown_item.dart';
part 'social_login.dart';
part 'toast_message.dart';
part 'zoomable_image.dart';
part 'terms_and_conditions_check_box.dart';
